2024-09-29 17:21:31 - [INFO] - --------------------------------------------------
2024-09-29 17:21:31 - [INFO] - ORQ 2 PRUEBA TECNICA ORIGINACION COBRANZA
2024-09-29 17:21:31 - [INFO] - --------------------------------------------------
2024-09-29 17:21:31 - [INFO] - Guardado logs en: C:\Users\juavila\Documents\Prueba_tecnica_Originacion_Cobranza\vghu-prueba-tecnica-originacion-cobranza\logs\20240929_172131_orq_2_prueba_tecnica_originacion_cobranza.log
2024-09-29 17:21:37 - [INFO] - Versión de Orquestador: 1.3.6
2024-09-29 17:21:37 - [INFO] - Inicializando Ejecución de Orquestador
2024-09-29 17:21:37 - [INFO] - Se agregaron 2 consultas al plan de ejecucion
2024-09-29 17:21:37 - [INFO] - Inicia la ejecucion de la tarea ExtractTransformLoad
2024-09-29 17:21:37 - [INFO] - ------------------------------------------------
2024-09-29 17:21:37 - [INFO] - Ejecutando Paso ** ExtractTransformLoad **
2024-09-29 17:21:37 - [INFO] - Paso ExtractTransformLoad finalizado en 0.0s
2024-09-29 17:21:37 - [INFO] - Finalizó la ejecucion de la tarea ExtractTransformLoad, duracion: 00:00.0
2024-09-29 17:21:37 - [INFO] - Inicia la ejecucion de la tarea TransformarDatosPython
2024-09-29 17:21:37 - [INFO] - ------------------------------------------------
2024-09-29 17:21:37 - [INFO] - Ejecutando Paso ** TransformarDatosPython **
2024-09-29 17:21:37 - [INFO] - Datos cargados correctamente.
2024-09-29 17:21:37 - [INFO] - Productos limpios.
2024-09-29 17:21:37 - [INFO] - Concatenación de segmentos en obligaciones.
2024-09-29 17:21:37 - [INFO] - Concatenación de segmentos en tasas.
2024-09-29 17:21:37 - [INFO] - Tasas asignadas.
2024-09-29 17:21:37 - [INFO] - Tasa efectiva y valor final calculados.
2024-09-29 17:21:37 - [INFO] - Resumen por cliente calculado.
2024-09-29 17:21:37 - [ERROR] - Ocurrió un error inesperado durante el proceso: Cannot save file into a non-existent directory: 'C:\Users\juavila\Documents\Prueba_tecnica_Originacion_Cobranza\vghu-prueba-tecnica-originacion-cobranza\src\vghu_prueba_tecnica_originacion_cobranza\static\Resultados'
2024-09-29 17:21:37 - [ERROR] - Error: Falló el paso TransformarDatosPython, Error Encontrado: Cannot save file into a non-existent directory: 'C:\Users\juavila\Documents\Prueba_tecnica_Originacion_Cobranza\vghu-prueba-tecnica-originacion-cobranza\src\vghu_prueba_tecnica_originacion_cobranza\static\Resultados'
2024-09-29 17:21:37 - [ERROR] - ------------ ERROR EN EJECUCION  ---------------------
2024-09-29 17:21:37 - [ERROR] - El Orquestador ha encontrado un Error en el proceso
2024-09-29 17:21:37 - [ERROR] - Error en Orq 2 prueba tecnica originacion cobranza
2024-09-29 17:21:37 - [ERROR] - Tipo de Excepcion : OSError 
2024-09-29 17:21:37 - [ERROR] - Mensaje : Cannot save file into a non-existent directory: 'C:\Users\juavila\Documents\Prueba_tecnica_Originacion_Cobranza\vghu-prueba-tecnica-originacion-cobranza\src\vghu_prueba_tecnica_originacion_cobranza\static\Resultados'
2024-09-29 17:21:37 - [ERROR] - Stack Trace:
2024-09-29 17:21:37 - [ERROR] - ----> File : C:\Users\juavila\Documents\Prueba_tecnica_Originacion_Cobranza\vghu-prueba-tecnica-originacion-cobranza\.venv\lib\site-packages\orquestador2\orquestador2.py , Line : 611, Func.Name : ejecutar, Message : self.reStarter(sx, maxTries=mT)
2024-09-29 17:21:37 - [ERROR] - ----> File : C:\Users\juavila\Documents\Prueba_tecnica_Originacion_Cobranza\vghu-prueba-tecnica-originacion-cobranza\.venv\lib\site-packages\orquestador2\orquestador2.py , Line : 355, Func.Name : reStarter, Message : raise ex
2024-09-29 17:21:37 - [ERROR] - ----> File : C:\Users\juavila\Documents\Prueba_tecnica_Originacion_Cobranza\vghu-prueba-tecnica-originacion-cobranza\.venv\lib\site-packages\orquestador2\orquestador2.py , Line : 350, Func.Name : reStarter, Message : step.ejecutar()
2024-09-29 17:21:37 - [ERROR] - ----> File : C:\Users\juavila\Documents\Prueba_tecnica_Originacion_Cobranza\vghu-prueba-tecnica-originacion-cobranza\src\vghu_prueba_tecnica_originacion_cobranza\etl.py , Line : 307, Func.Name : ejecutar, Message : raise e
2024-09-29 17:21:37 - [ERROR] - ----> File : C:\Users\juavila\Documents\Prueba_tecnica_Originacion_Cobranza\vghu-prueba-tecnica-originacion-cobranza\src\vghu_prueba_tecnica_originacion_cobranza\etl.py , Line : 300, Func.Name : ejecutar, Message : df_resumen_final.to_excel(self.getFolderPath() + "Resultados/resumen_por_cliente.xlsx", index=False)
2024-09-29 17:21:37 - [ERROR] - ----> File : C:\Users\juavila\Documents\Prueba_tecnica_Originacion_Cobranza\vghu-prueba-tecnica-originacion-cobranza\.venv\lib\site-packages\pandas\util\_decorators.py , Line : 333, Func.Name : wrapper, Message : return func(*args, **kwargs)
2024-09-29 17:21:37 - [ERROR] - ----> File : C:\Users\juavila\Documents\Prueba_tecnica_Originacion_Cobranza\vghu-prueba-tecnica-originacion-cobranza\.venv\lib\site-packages\pandas\core\generic.py , Line : 2417, Func.Name : to_excel, Message : formatter.write(
2024-09-29 17:21:37 - [ERROR] - ----> File : C:\Users\juavila\Documents\Prueba_tecnica_Originacion_Cobranza\vghu-prueba-tecnica-originacion-cobranza\.venv\lib\site-packages\pandas\io\formats\excel.py , Line : 943, Func.Name : write, Message : writer = ExcelWriter(
2024-09-29 17:21:37 - [ERROR] - ----> File : C:\Users\juavila\Documents\Prueba_tecnica_Originacion_Cobranza\vghu-prueba-tecnica-originacion-cobranza\.venv\lib\site-packages\pandas\io\excel\_openpyxl.py , Line : 61, Func.Name : __init__, Message : super().__init__(
2024-09-29 17:21:37 - [ERROR] - ----> File : C:\Users\juavila\Documents\Prueba_tecnica_Originacion_Cobranza\vghu-prueba-tecnica-originacion-cobranza\.venv\lib\site-packages\pandas\io\excel\_base.py , Line : 1246, Func.Name : __init__, Message : self._handles = get_handle(
2024-09-29 17:21:37 - [ERROR] - ----> File : C:\Users\juavila\Documents\Prueba_tecnica_Originacion_Cobranza\vghu-prueba-tecnica-originacion-cobranza\.venv\lib\site-packages\pandas\io\common.py , Line : 749, Func.Name : get_handle, Message : check_parent_directory(str(handle))
2024-09-29 17:21:37 - [ERROR] - ----> File : C:\Users\juavila\Documents\Prueba_tecnica_Originacion_Cobranza\vghu-prueba-tecnica-originacion-cobranza\.venv\lib\site-packages\pandas\io\common.py , Line : 616, Func.Name : check_parent_directory, Message : raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
2024-09-29 17:21:37 - [INFO] - Registro de la Ejecución: {'nomb_paquete': 'vghu_prueba_tecnica_originacion_cobranza', 'nomb_proceso': 'Orq 2 prueba tecnica originacion cobranza', 'fecha_inicio': 20240929, 'hora_inicio': '17:21:37', 'fecha_fin': 20240929, 'hora_fin': '17:21:37', 'duracion': 0.54, 'estado_fin': 'ERROR', 'texto_fin': "Cannot save file into a non-existent directory: 'C:\\Users\\juavila\\Documents\\Prueba_tecnica_Originacion_Cobranza\\vghu-prueba-tecnica-originacion-cobranza\\src\\vghu_prueba_tecnica_originacion_cobranza\\static\\Resultados'"}
2024-09-29 17:21:37 - [INFO] - Duración Total en 0.52s
2024-09-29 17:21:37 - [INFO] - ------------------------------------------------
